#!/bin/bash
echo "Activando modo hotspot..."
sudo tee /etc/NetworkManager/conf.d/unmanaged.conf << 'CONF'
[keyfile]
unmanaged-devices=interface-name:wlan0
CONF
sudo systemctl restart NetworkManager
sleep 2
sudo ip addr add 192.168.4.1/24 dev wlan0 2>/dev/null || true
sudo systemctl unmask hostapd
sudo systemctl enable hostapd
sudo systemctl restart hostapd
sudo systemctl restart dnsmasq
echo "Modo hotspot activo. Red: FonoScreen / fonoscreen2025"
